# Generated by Django 4.0.4 on 2022-05-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('description', models.TextField(max_length=255)),
                ('cost', models.IntegerField(max_length=255)),
                ('phone', models.IntegerField(max_length=11)),
                ('mail', models.CharField(max_length=255)),
                ('time_create', models.DateField(auto_now_add=True)),
                ('time_update', models.DateField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
